# Generated by Django 6.0.1 on 2026-01-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_prefix', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='attendance.lecture')),
            ],
        ),
    ]
