# Generated by Django 6.0.1 on 2026-01-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_unique_together'),
        ('network_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_prefix', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='attendance.attendancesession')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassroomNetwork',
        ),
    ]
